# wrangler.toml
name = "recruva"
main = "./build/server/index.js"  # Main entry point

# Your existing KV namespace configuration
kv_namespaces = [
  { id = "MY_KV", binding = "MY_KV" }
]

# Additional recommended configurations
compatibility_date = "2025-01-01"
workers_dev = true